version: 2
models:
  - name: indicadores_macroeconomicos
    description: "Indicadores macro mensais: Selic, IPCA, dólar, PIB e inadimplência"
    columns:
      - name: mes_ref
        description: "Mes de referencia do indicador"
        tests:
          - not_null
          - unique

      - name: selic_media_mes
        description: "Media da taxa Selic no mes de referencia"
        tests:
          - not_null

      - name: pib_valor_mes
        description: "Valor mensal do PIB disponibilizado pelo BCB"

      - name: inadimplencia_media_mes
        description: "Taxa média mensal de inadimplência"
